image: ubuntu:24.04

before_script:
  - apt-get update -y
  - apt-get install -y build-essential cmake git

stages:
    - test

test:
    stage: test
    script:
        - mkdir _build && cd _build
        - cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
        - make -j$(nproc)
        - ctest --output-junit test_results.xml
    artifacts:
        when: always
        paths:
            - _build/test_results.xml
        reports:
            junit: _build/test_results.xml