name: Sync Subtrees

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'If true, don’t push any changes (for testing only).'
        required: true
        default: true
        type: boolean
      testMerge:
        description: 'Run in test mode, pushing to a test branch.'
        required: true
        default: false
        type: boolean

jobs:
  sync-subtrees:
    runs-on: ubuntu-latest
    steps:
      - name: Run sync-subtrees-action
        uses: usgs-coupled/sync-subtrees-action@main
        with:
          dryRun: ${{ inputs.dryRun }}
          testMerge: ${{ inputs.testMerge }}
          repoName: ${{ github.event.repository.name }}
          defaultRef: ${{ github.event.repository.default_branch }}
          runNumber: ${{ github.run_number }}
          sshKey: ${{ secrets.SSH_PRIVATE_KEY }}
          repoOwner: ${{ github.repository_owner }}
